from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Literal

import numpy as np
import pandas as pd

from .fmnist_multiclass_benchmark import (
    MulticlassFederation,
    LAYOUT as MLP_LAYOUT,
    initialize_mlp,
    loss_and_gradient as mlp_loss_and_gradient,
    predictive_metrics as mlp_predictive_metrics,
)
from .fmnist_cnn_benchmark import (
    LAYOUT as CNN_LAYOUT,
    initialize_cnn,
    loss_and_gradient as cnn_loss_and_gradient,
    predictive_metrics as cnn_predictive_metrics,
)


Architecture = Literal["mlp", "cnn"]
Method = Literal["event", "strom", "ef_topk", "sign_ef", "dense"]


@dataclass(frozen=True)
class FinalBaselineConfig:
    local_steps: int = 5
    local_lr: float = 0.1
    batch_size: int = 32
    regularization: float = 1e-4
    rounds: int = 150
    eval_stride: int = 15
    rho: float = 0.999
    threshold: float = 0.025
    jump0: float = 0.005
    jump_scale: float = 100.0
    jump_exponent: float = 0.1
    topk_fraction: float = 0.025
    strom_threshold: float = 0.005


def _architecture_ops(architecture: Architecture):
    if architecture == "mlp":
        return MLP_LAYOUT, initialize_mlp, mlp_loss_and_gradient, mlp_predictive_metrics
    if architecture == "cnn":
        return CNN_LAYOUT, initialize_cnn, cnn_loss_and_gradient, cnn_predictive_metrics
    raise ValueError(architecture)


def _local_delta(
    w_server: np.ndarray,
    X: np.ndarray,
    y: np.ndarray,
    *,
    config: FinalBaselineConfig,
    rng: np.random.Generator,
    layout,
    loss_grad,
) -> np.ndarray:
    w_local = w_server.copy()
    n = len(y)
    for _ in range(config.local_steps):
        ids = rng.integers(0, n, size=config.batch_size)
        _, _, gradient = loss_grad(
            w_local,
            X[ids],
            y[ids],
            layout=layout,
            regularization=config.regularization,
            need_gradient=True,
        )
        w_local -= config.local_lr * gradient
    return (w_local - w_server).astype(np.float32, copy=False)


def run_final_baseline(
    *,
    federation: MulticlassFederation,
    architecture: Architecture,
    method: Method,
    config: FinalBaselineConfig,
    seed: int = 70707,
) -> dict[str, float | int | str]:
    """Run one frozen FedAvg baseline and account for exact bidirectional replay.

    All methods use identical local SGD.  The compressed methods expose the exact
    server-side packet stream generated by their uplink.  A synchronized client
    can reproduce the new server model by replaying that stream.  Conservative
    unicast accounting charges every client a 32-bit catch-up request per round
    and chooses the cheaper of exact replay and a float32 model checkpoint.
    """
    layout, initialize, loss_grad, metrics = _architecture_ops(architecture)
    rng = np.random.default_rng(seed)
    n_clients = federation.n_clients
    d = int(layout.dimension)
    address_bits = int(math.ceil(math.log2(d)))
    pulse_bits = address_bits + 1
    topk = max(1, int(round(config.topk_fraction * d)))
    weights = federation.weights.astype(float)
    weights /= np.sum(weights)

    w = initialize(layout=layout, seed=7777, scale=0.5)
    event_state = np.zeros((n_clients, d), dtype=np.float32)
    strom_state = np.zeros((n_clients, d), dtype=np.float32)
    residual = np.zeros((n_clients, d), dtype=np.float32)

    uplink_payload = 0
    uplink_packetized = 0
    messages = 0
    coordinate_events = 0
    delta_norms: list[float] = []
    history_rows: list[dict[str, float | int]] = []
    round_replay_packetized: list[int] = []

    evidence_gain = 1.0 / config.local_lr

    for rnd in range(1, config.rounds + 1):
        deltas: list[np.ndarray] = []
        for client in range(n_clients):
            delta = _local_delta(
                w,
                federation.client_X[client],
                federation.client_y[client],
                config=config,
                rng=rng,
                layout=layout,
                loss_grad=loss_grad,
            )
            deltas.append(delta)
            delta_norms.append(float(np.linalg.norm(delta)))

        aggregate = np.zeros(d, dtype=np.float32)
        replay_this_round = 0

        if method == "event":
            event_state *= config.rho
            jump = config.jump0 * (1.0 + rnd / config.jump_scale) ** (-config.jump_exponent)
            for client in range(n_clients):
                event_state[client] += evidence_gain * float(weights[client]) * deltas[client]
                mask = np.abs(event_state[client]) >= config.threshold
                count = int(np.sum(mask))
                if count:
                    signs = np.sign(event_state[client, mask]).astype(np.int8)
                    aggregate[mask] += jump * signs.astype(np.float32)
                    event_state[client, mask] = 0.0
                    bits = count * pulse_bits
                    packet = bits + 64
                    uplink_payload += bits
                    uplink_packetized += packet
                    replay_this_round += packet
                    messages += 1
                    coordinate_events += count

        elif method == "strom":
            tau = float(config.strom_threshold)
            for client in range(n_clients):
                strom_state[client] += evidence_gain * float(weights[client]) * deltas[client]
                mask = np.abs(strom_state[client]) >= tau
                count = int(np.sum(mask))
                if count:
                    signs = np.sign(strom_state[client, mask]).astype(np.int8)
                    aggregate[mask] += tau * signs.astype(np.float32)
                    # Residual-conserving Strom pulse: subtract the transmitted quantum.
                    strom_state[client, mask] -= tau * signs.astype(np.float32)
                    bits = count * pulse_bits
                    packet = bits + 64
                    uplink_payload += bits
                    uplink_packetized += packet
                    replay_this_round += packet
                    messages += 1
                    coordinate_events += count

        elif method == "ef_topk":
            for client in range(n_clients):
                residual[client] += float(weights[client]) * deltas[client]
                ids = np.argpartition(np.abs(residual[client]), -topk)[-topk:]
                values = residual[client, ids].copy()
                aggregate[ids] += values
                residual[client, ids] = 0.0
                bits = topk * (32 + address_bits)
                packet = bits + 64
                uplink_payload += bits
                uplink_packetized += packet
                replay_this_round += packet
                messages += 1

        elif method == "sign_ef":
            for client in range(n_clients):
                residual[client] += float(weights[client]) * deltas[client]
                scale = float(np.mean(np.abs(residual[client])))
                if scale > 0:
                    compressed = (scale * np.sign(residual[client])).astype(np.float32)
                    aggregate += compressed
                    residual[client] -= compressed
                bits = d + 32
                packet = bits + 64
                uplink_payload += bits
                uplink_packetized += packet
                replay_this_round += packet
                messages += 1

        elif method == "dense":
            for client in range(n_clients):
                aggregate += float(weights[client]) * deltas[client]
                bits = 32 * d
                packet = bits + 64
                uplink_payload += bits
                uplink_packetized += packet
                replay_this_round += packet
                messages += 1
        else:
            raise ValueError(method)

        w += aggregate
        round_replay_packetized.append(int(replay_this_round))

        if rnd == 1 or rnd % config.eval_stride == 0 or rnd == config.rounds:
            train_obj, train_ce, _, _, _, _ = metrics(
                w,
                federation.X_train_eval,
                federation.y_train_eval,
                layout=layout,
                regularization=config.regularization,
            )
            _, test_ce, test_acc, macro_acc, worst_acc, _ = metrics(
                w,
                federation.X_test,
                federation.y_test,
                layout=layout,
                regularization=config.regularization,
            )
            history_rows.append(
                {
                    "round": rnd,
                    "train_objective": train_obj,
                    "train_ce": train_ce,
                    "test_ce": test_ce,
                    "test_accuracy": test_acc,
                    "macro_accuracy": macro_acc,
                    "worst_class_accuracy": worst_acc,
                    "uplink_packetized_bits": uplink_packetized,
                }
            )

    history = pd.DataFrame(history_rows)
    train_obj, train_ce, _, _, _, _ = metrics(
        w,
        federation.X_train_eval,
        federation.y_train_eval,
        layout=layout,
        regularization=config.regularization,
    )
    _, test_ce, test_acc, macro_acc, worst_acc, per_class = metrics(
        w,
        federation.X_test,
        federation.y_test,
        layout=layout,
        regularization=config.regularization,
    )

    # End-to-end synchronization accounting.
    checkpoint_payload = 32 * d
    checkpoint_packet = checkpoint_payload + 64
    request_bits = 32

    # Initial model synchronization is charged explicitly.
    broadcast_down = checkpoint_packet
    unicast_down = n_clients * checkpoint_packet
    replay_rounds = 0
    checkpoint_rounds = 0
    for replay_bits in round_replay_packetized:
        if replay_bits <= checkpoint_packet:
            replay_rounds += 1
        else:
            checkpoint_rounds += 1
        broadcast_down += min(replay_bits, checkpoint_packet)
        unicast_down += n_clients * (request_bits + min(replay_bits, checkpoint_packet))

    result: dict[str, float | int | str] = {
        "architecture": architecture,
        "method": method,
        "dimension": d,
        "rounds": config.rounds,
        "local_steps": config.local_steps,
        "local_lr": config.local_lr,
        "final_train_objective": float(train_obj),
        "final_train_ce": float(train_ce),
        "final_test_ce": float(test_ce),
        "final_test_accuracy": float(test_acc),
        "final_macro_accuracy": float(macro_acc),
        "final_worst_class_accuracy": float(worst_acc),
        "whole_train_objective": float(history["train_objective"].mean()),
        "uplink_payload_bits": int(uplink_payload),
        "uplink_packetized_bits": int(uplink_packetized),
        "broadcast_downlink_bits": int(broadcast_down),
        "unicast_hybrid_downlink_bits": int(unicast_down),
        "broadcast_total_bits": int(uplink_packetized + broadcast_down),
        "unicast_hybrid_total_bits": int(uplink_packetized + unicast_down),
        "messages": int(messages),
        "coordinate_events": int(coordinate_events),
        "events_per_message": float(coordinate_events / messages) if messages else 0.0,
        "mean_delta_norm": float(np.mean(delta_norms)),
        "replay_rounds": int(replay_rounds),
        "checkpoint_rounds": int(checkpoint_rounds),
        "rho": float(config.rho),
        "threshold": float(config.threshold),
        "jump0": float(config.jump0),
        "jump_exponent": float(config.jump_exponent),
        "topk_fraction": float(config.topk_fraction),
        "strom_threshold": float(config.strom_threshold),
    }
    for cls, acc in enumerate(per_class):
        result[f"class_{cls}_accuracy"] = float(acc)
    return result
